### ISSUE TITLE
Allow for specific division models

### ISSUE THREAD

**Issue by FrickTobias** [chan-labsite/SC-Track#2]
I'm experience a reasonable amount of division detection errors and they are both false positives and false negatives.

I appreciate divsions can look very differently depending on cell line so I was thinking if it would be possible to customize the pipeline with a user-supplied model. I've had a lot of success previously with training a small ResNet for scoring the division and I was wondering if it would be possible to include this into the pipeline?

False positive example 1:
 - Incorrect: 13-0 => 13-1 & 13-2 

![track_visualization-0554](https://github.com/chan-labsite/SC-Track/assets/17293950/213971c4-de61-4905-8d28-6dd0344c0c38)

![track_visualization-0555](https://github.com/chan-labsite/SC-Track/assets/17293950/82fc95b6-22d0-46ac-a491-66a3b940d5dd)

False positive example 2:
 - Incorrect: 13-2 => 13-3 & 13-4

![track_visualization-0667](https://github.com/chan-labsite/SC-Track/assets/17293950/3aa34779-f71e-4454-9511-4d7c7afdf780)

![track_visualization-0668](https://github.com/chan-labsite/SC-Track/assets/17293950/ac75657c-3583-40d8-bc63-dfb8d4d4ae36)

False negative example 1:
 - Correct: 2-0 => 2-1 & 2-2

![track_visualization-0156](https://github.com/chan-labsite/SC-Track/assets/17293950/405f2b7d-4667-4408-a4d6-577c2ba11d61)

![track_visualization-0157](https://github.com/chan-labsite/SC-Track/assets/17293950/1ec1b3ae-398b-41cf-8ea9-25b65044cf8b)

**Comment by chan-labsite** [comment]
Hi Tobias, I think Chengxin has responded to the issue you raised here in your earlier post. Briefly, SC-Track would require G1/G2, S and M-phase cell cycle classifications in order to utilise cell cycle phase for improving the accuracy of mother and daughter linkages. Without the cell cycle phase, SC-Track will resort to the cellular mask predict cell division events which has higher levels of inaccuracies.

I think it is a good idea to have a more generalised pipeline where the user can provide the mitosis classification only in the cell segmentations to help with improving the cell tracking accuracy. However, this would require significant alterations in our cell cycle classification pipelines. We will aim to get this implemented in future updates of SC-Track.

**Comment by FrickTobias** [comment]
> Hi Tobias, I think Chengxin has responded to the issue you raised here in your earlier post. Briefly, SC-Track would require G1/G2, S and M-phase cell cycle classifications in order to utilise cell cycle phase for improving the accuracy of mother and daughter linkages. Without the cell cycle phase, SC-Track will resort to the cellular mask predict cell division events which has higher levels of inaccuracies.
> 
> I think it is a good idea to have a more generalised pipeline where the user can provide the mitosis classification only in the cell segmentations to help with improving the cell tracking accuracy. However, this would require significant alterations in our cell cycle classification pipelines. We will aim to get this implemented in future updates of SC-Track.

Okay good to know! 

For now I'll resort to Chengxin's reply in the issue #1 and see if I can turn it off and solve it with post-processing.

Thanks for the super quick and informative reply!
